navikt/common-java-modules

pom.xml

Note that this may break tests that are not
properly isolated. Avoid using class fields
that are reused between test methods. Make sure
to create new instances of such fields using
@BeforeEach (JUnit5) or similar.

BREAKING: Set reuseForks=true in mor-pom

---

bom/pom.xml
nais/pom.xml
nais/src/main/java/no/nav/common/nais/utils/NaisYamlUtils.java
nais/src/test/java/no/nav/common/nais/utils/NaisYamlUtilsTest.java
nais/src/test/resources/min-nais-templated-example.yaml

deploy-cli bruker "VAR" og "VARS" for injecting av variabler fra byggejobben.
For å starte appen lokalt kan det være kjekt å gjenbruke denne templatingen.

la til stotte for lesing av templated yaml-filer

---

api-app/src/main/java/no/nav/apiapp/config/ApiAppConfigurator.java
api-app/src/main/java/no/nav/apiapp/config/Konfigurator.java

Kunne brukt `azureADB2CLogin(AzureADB2CConfig azureADB2CConfig)` også, men den står som deprecated.

La til mulighet for å sende inn config for validering med Azure AD

---

selftest/src/main/java/no/nav/sbl/dialogarena/common/web/selftest/domain/SelftestResult.java
selftest/src/test/java/no/nav/sbl/dialogarena/common/web/selftest/domain/SelftestResultTest.java

Noen som evt husker noe om hvorfor `DISABLED` skulle føre til `WARNING` status for hele selftesten?

Disabled selftester burde ikke påvirke aggregertstatus

---

api-app/src/main/java/no/nav/apiapp/ApiApp.java
bom/pom.xml
log/pom.xml
log/src/main/java/no/nav/sbl/util/LogUtils.java

jersey bruker java.util.Loggin (JUL), logger derifra blir per i dag
derfor ikke korrekt formattert (JSON) siden de ikke går gjennon logback

oppsett for jul-to-slf4j

---

bom/pom.xml
cxf/pom.xml

For å rette feil: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found

Legg til avhengighet til saaj-impl i cxf modul

---

test/src/main/java/no/nav/common/test/ssl/SSLTestUtils.java
test/src/main/java/no/nav/common/test/ssl/TrustAllX509TrustManager.java

Gjør det lettere å sette OkHttp uten sertifikat validering, e.g;
```java
RestClient.setBaseClient(
RestClient
.baseClientBuilder()
.sslSocketFactory(new TrustAllSSLSocketFactory(), new TrustAllX509TrustManager())
.build()
);
```

Flyttet X509TrustManager til egen fil

---

health/src/main/java/no/nav/common/health/selftest/SelftestHtmlGenerator.java
health/src/main/resources/selftest/SelfTestPage.html
health/src/test/java/no/nav/common/health/selftest/SelftestHtmlGeneratorTest.java
health/src/test/resources/expected-selftest.html

Det er satt opp noen regler i SiteScope som forventer å finne en tag med id "driftsMelding" som inneholder feilede komponenter.

La til driftsmelding med feilede komponenter i selftest HTML.

---

types/pom.xml
types/src/main/java/no/nav/common/types/identer/AktorId.java
types/src/main/java/no/nav/common/types/identer/AzureObjectId.java
types/src/main/java/no/nav/common/types/identer/EnhetId.java
types/src/main/java/no/nav/common/types/identer/Fnr.java
types/src/main/java/no/nav/common/types/identer/Id.java
types/src/main/java/no/nav/common/types/identer/NavIdent.java
types/src/test/java/no/nav/types/identer/AktorIdTest.java
types/src/test/java/no/nav/types/identer/AzureObjectIdTest.java
types/src/test/java/no/nav/types/identer/EnhetIdTest.java
types/src/test/java/no/nav/types/identer/FnrTest.java
types/src/test/java/no/nav/types/identer/NavIdentTest.java

Json modulen bruker en ObjectMapper med custom config som ikke får deserialisert domenetypene uten å legge til @JsonCreator

Fikset deserialisering av domenetyper med JsonUtils

---

abac/src/main/java/no/nav/common/abac/Pep.java
abac/src/main/java/no/nav/common/abac/VeilarbPep.java
abac/src/main/java/no/nav/common/abac/XacmlRequestBuilder.java
abac/src/test/java/no/nav/common/abac/VeilarbPepTest.java
abac/src/test/resources/xacmlrequest-harTilgangTilEnhet.json
abac/src/test/resources/xacmlrequest-harTilgangTilEnhetMedSperre.json

Den tidligere sjekken på enhet sjekket på enhet med kontorsperre som ikke blir riktig for eksterne brukere som alltid vil få permit.
Fikset sjekken til å bruke riktig ABAC resource og byttet navn på nåværende sjekk til `enhetMedSperre`.

Fikset sjekk på tilgang til enhet og la til ny tilgangssjekk

---

.github/workflows/main.yml

https://www.zdnet.com/article/google-to-github-times-up-this-unfixed-high-severity-security-bug-affects-developers/

Fikset set-env i workflow som har blitt erstattet med $GITHUB_ENV

---

bom/pom.xml

Fikser sikkerhetshull ved å oppgradere til >= 3.4.1

Bump cxf til siste versjon (3.4.2)

---

kafka/src/main/java/no/nav/common/kafka/consumer/KafkaConsumerClient.java
kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessor.java

Avbryt polling med wakeup() og skru av topic partition executors under opprydding

Bedre håndtering av shutdown for consumer client

---

kafka/src/main/java/no/nav/common/kafka/consumer/util/TopicConsumerMetrics.java
kafka/src/main/java/no/nav/common/kafka/producer/util/KafkaProducerClientWithMetrics.java

Tegn som "." og "-" blir byttet ut med "_" når det blir hentet av prometheus så det er ikke farlig å la det være som det er, men det kan være litt forvirrende at navnene er annerledes i prometheus enn det de er i koden.

Fikset på kafka metrikk navn

---

kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessor.java
kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessorConfig.java
kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/util/KafkaConsumerRecordProcessorBuilder.java
kafka/src/test/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessorIntegrationTest.java

Mulighet for konfigurering av timeouts og batch-størrelse via config-objekt. Builder-klasse for KafkaConsumerRecordProcessor. Høyere default verdier for timeouts.

Legg til støtte for konfigurering av KafkaConsumerRecordProcessor

---

client/src/main/java/no/nav/common/client/utils/graphql/GraphqlErrorException.java
client/src/main/java/no/nav/common/client/utils/graphql/GraphqlNoDataException.java
client/src/main/java/no/nav/common/client/utils/graphql/GraphqlUtils.java

Istedenfor å kaste vanlige exceptions så er det bedre å kaste custom exceptions som gir brukeren av klienten mulighet til å gjøre feilhåndtering med informasjon fra responsen.

Custom exceptions for error og manglende data i Graphql

---

rest/src/main/java/no/nav/common/rest/filter/ConsumerIdComplianceFilter.java
rest/src/test/java/no/nav/common/rest/filter/ConsumerIdComplianceFilterTest.java

Alle requests som blir sendt til en backend burde inneholde headeren Nav-Consumer-Id slik at vi får kontroll over hvem som sender requests. Tanken er å kun skru på enforcement i dev, slik at det ikke påvirker ting som kjører i prod.

La til consumer-id compliance filter

---

api-app/README.md
api-app/src/main/java/no/nav/apiapp/ApiApp.java
api-app/src/main/java/no/nav/apiapp/ApiAppServletContextListener.java

Sensu tar imot InfluxDB-metrics fra ApiApp.
Sensu eksisterer ikke i GCP, og en annen metrics-tjeneste må i stedet benyttes.
InfluxDB-metrics trengs ikke i alle apper som bruker ApiApp, så et alternativ her er å deaktivere den.
Denne endringen legger til environment-variabelet `DISABLE_SENSU_METRICS`, som kan settes til `true` for å skru av sensu/influx-metrics.

Legger til støtte for å skru av Sensu-metrics

---

client/src/main/java/no/nav/common/client/nom/NomClientImpl.java

På grunn av situasjonen i Axsys, der det ikke er ryddet opp i utgåtte identer, vill dette logges ofte uten at det egentlig er en error. Dette er i alle fall tilfellet til veilarbveileder.

Endret log innslag fra error til info

---

bom/pom.xml
kafka/pom.xml
kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/OracleConsumerRepository.java
kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/PostgresConsumerRepository.java
kafka/src/main/java/no/nav/common/kafka/producer/feilhandtering/OracleProducerRepository.java
kafka/src/main/java/no/nav/common/kafka/producer/feilhandtering/PostgresProducerRepository.java
kafka/src/main/java/no/nav/common/kafka/spring/DatabaseUtils.java
kafka/src/main/java/no/nav/common/kafka/spring/OracleJdbcTemplateConsumerRepository.java
kafka/src/main/java/no/nav/common/kafka/spring/OracleJdbcTemplateProducerRepository.java
kafka/src/main/java/no/nav/common/kafka/spring/PostgresJdbcTemplateConsumerRepository.java
kafka/src/main/java/no/nav/common/kafka/spring/PostgresJdbcTemplateProducerRepository.java
kafka/src/main/java/no/nav/common/kafka/util/DatabaseUtils.java
kafka/src/test/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessorIntegrationTest.java
kafka/src/test/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRepositoryTest.java
kafka/src/test/java/no/nav/common/kafka/producer/feilhandtering/KafkaProducerRecordProcessorIntegrationTest.java
kafka/src/test/java/no/nav/common/kafka/producer/feilhandtering/KafkaProducerRepositoryTest.java

Måten connections til databasen ble hentet på tok ikke høyde for transaksjoner ved bruk av Spring. Endrer derfor implementasjonen til å være konkret rettet mot å bruke Spring. Andre implementasjoner kan implementeres ved behov.

Endre impl av Kafka-repos til å bruke Spring JdbcTemplate

---

kafka/src/main/java/no/nav/common/kafka/consumer/KafkaConsumerClientImpl.java
kafka/src/test/java/no/nav/common/kafka/consumer/KafkaConsumerClientTest.java

Messages will be lost if not seeking back since the next poll will continue polling newer messages, disregarding which offset that has been commited.

Seek back on failed messages in Kafka consumer

---

kafka/src/main/java/no/nav/common/kafka/consumer/KafkaConsumerClientImpl.java

Hvis en partisjon blir revoked eller en record feiler så må offsets håndteres riktig ved å seeke manuelt, hvis ikke så vil kafka hoppe over records i neste kall til poll()

Fikse seeking av offsets når partisjoner blir revoked eller records feiler

---

bom/pom.xml
job/src/main/java/no/nav/common/job/leader_election/ShedLockLeaderElectionClient.java
job/src/test/java/no/nav/common/job/leader_election/ShedLockLeaderElectionClientTest.java

Istedenfor at brukere av ShedLockLeaderElectionClient må sørge for å polle jevnlig for at samme pod skal bli leder, så er det bedre hvis ShedLockLeaderElectionClient gjør dette selv.
Dette fikser problemer hvor man f.eks har veldig lange jobber og man ikke får pollet leader election klienten nok slik at en annen instanse blir leder mens den forrige lederen utfører den lange jobben.

Improve shedlock

---

client/src/main/java/no/nav/common/client/axsys/AxsysClientImpl.java
client/src/main/java/no/nav/common/client/axsys/AxsysV2ClientImpl.java
client/src/main/java/no/nav/common/client/axsys/BaseAxsysClient.java
client/src/test/java/no/nav/common/client/axsys/AxsysClientTest.java

v1 og v2 versjonene er kompatible, men v2 krever azure-ad token tilsvarende NomClient.
Majoriteten av `AxsysClientImpl` er flyttet til `BaseAxsysClient` som deretter brukes av begge axsys klientene.

Legge til client for axsys v2 api

---

kafka/src/main/java/no/nav/common/kafka/consumer/util/TopicConsumerMetrics.java
kafka/src/main/java/no/nav/common/kafka/producer/util/KafkaProducerClientWithMetrics.java

Hvis man oppdaterer vanlig HashMap så vil det bli kastet et exception når man endrer det samtidig fra forskjellige tråder.

Bruk concurrent maps for kafka metrikker

---

rest/src/test/java/no/nav/common/rest/client/RestClientTest.java

Noen ganger så er det 31-tegn istedenfor 32-tegn, håndter begge tilfeller

Gjør regex test på call-id mer robust

---

auth/src/main/java/no/nav/common/auth/oidc/filter/OidcAuthenticationFilter.java
auth/src/main/java/no/nav/common/auth/oidc/filter/OidcAuthenticator.java
auth/src/main/java/no/nav/common/auth/oidc/filter/OidcAuthenticatorConfig.java
auth/src/test/java/no/nav/common/auth/oidc/filter/OidcAuthenticationFilterTest.java

Revertering av endringene i #581 og legger til muligheten for å konfigurere domain/path.
Gjøres fordi browseren ikke sender med domain/path i `Cookie` headeren, så man kan ikke kopiere disse derifra.

Gjør cookie domain/path konfigurerbart

---

token-client/src/main/java/no/nav/common/token_client/client/AzureAdOnBehalfOfTokenClient.java
token-client/src/main/java/no/nav/common/token_client/client/TokenXOnBehalfOfTokenClient.java
token-client/src/main/java/no/nav/common/token_client/utils/TokenUtils.java
token-client/src/test/java/no/nav/common/token_client/cache/CaffeineTokenCacheTest.java
token-client/src/test/java/no/nav/common/token_client/client/AzureAdMachineToMachineTokenClientTest.java
token-client/src/test/java/no/nav/common/token_client/client/AzureAdOnBehalfOfTokenClientTest.java
token-client/src/test/java/no/nav/common/token_client/client/TokenXOnBehalfOfTokenClientTest.java
token-client/src/test/java/no/nav/common/token_client/test_utils/TokenCreator.java

Istedenfor å bruke hash av tokenet som cache key, så bruker vi heller subject claimet i tokenet.
Dette vil gjøre at appen vil gjøre langt færre exchanges hvis den mottar forskjellige OBO-token med samme subject (bruker).

Forbedret caching av OBO-tokens

---

client/src/main/java/no/nav/common/client/aktoroppslag/PdlAktorOppslagClient.java

Tenker at en ny konstruktør kan gjøre det lettere å gå over til bruk av AzureAd mot pdl

AzureAd mot pdl skal ikke ha med Nav-Consumer-Token

---

bom/pom.xml

@AlexGaard 
Hadde problemer med at `kafka-avro-serializer` dro med seg `org.apache.kafka:kafka-clients:6.1.1-ccs` som dermed ble valgt i stedet for `org.apache.kafka:kafka-clients:3.1.1`. 
Basert på svar i https://stackoverflow.com/questions/61532385/kafka-dependencies-ccs-vs-ce så ser det ut som at confluent sine 7.x.x-pakker tilsvarer 3.x.x av Apache Kafka.
Ved å sette `kafka-avro-serializer` til `7.3.0` så går avhengighetene hos oss opp igjen, men jeg registrerer likevel en slags "mismatch" med at `kafka-avro-serializer` har en avhengighet til `7.3.0-ccs` av `kafka-clients`, så jeg satt denne versjonen eksplisitt til conlfluent sine releases også.
Kan være det er en bedre løsning på kabalen, f.eks. kun oppgradere `<avro-serializer.verion>` (hvis det er slik at vi har gjort et bevisst …

upgrade kafka and kafka-avro-serializer

---

rest/src/main/java/no/nav/common/rest/filter/JavaxSetHeaderFilter.java

Må ha javax i javaxversjon av filen frem til man er klar til å gå over til jakarta (finnes også en jakartaversjon: https://github.com/navikt/common-java-modules/blob/main/rest/src/main/java/no/nav/common/rest/filter/SetHeaderFilter.java)
For mer info, se https://github.com/navikt/common-java-modules/pull/666/files

Endre fra jakarta- til javaximport i javaxversjon

---

client/src/main/java/no/nav/common/client/aktoroppslag/PdlAktorOppslagClient.java
client/src/test/java/no/nav/common/client/aktoroppslag/PdlAktorOppslagClientTest.java
client/src/test/resources/no/nav/common/client/pdl/aktor_oppslag/hent-aktorid-ikke-funnet-response.json
client/src/test/resources/no/nav/common/client/pdl/aktor_oppslag/hent-aktorid-ugyldig-ident-response.json

Interfacet no.nav.common.client.aktoroppslag.AktorOppslagClient deklarerer checked exception IngenGjeldendeIdentException på hentFnr og hentAktorId. Denne patchen implementerer dette for Pdl GraphQL klienten.

ingenGjeldendeIdentException_for_PdlAktorOppslagClient

---

pom.xml

Nedgraderer mvn-source-plugin fordi versjon 3.3.x har en kjent bug som vi treffer ved release av common-java-modules: https://issues.apache.org/jira/browse/MSOURCES-143

nedgraderer plugin pga kjent bug

---

log/src/test/java/no/nav/common/log/LogTestHelpers.java
log/src/test/java/no/nav/common/log/LogbackSecureLogsTest.java
log/src/test/java/no/nav/common/log/LogbackStdoutJsonTest.java

testene oppleves som flaky, men ved å trekke ut "flushLogs" og samtidig sørge for å starte loggerContext'en etter at den stoppes så kjører i hvert fall disse testene lokalt

rydd opp rundt tester i log-modulen
