navikt/common-java-modules

- .github/workflows/main.yml
- bom/pom.xml
- cxf/pom.xml
- cxf/src/main/java/no/nav/sbl/dialogarena/common/cxf/CXFClient.java
- feed/pom.xml
- json/src/main/java/no/nav/json/DateConfiguration.java
- metrics/src/test/java/no/nav/metrics/aspects/CountAspectTest.java
- metrics/src/test/java/no/nav/metrics/aspects/TimerAspectTest.java
- pom.xml
- rest/pom.xml
- util/src/test/java/no/nav/sbl/util/XMLCalendarUtilsTest.java
This reverts commit 1cd56b1364efdd59794e29b930ec7b0113d3384a, reversing
changes made to ca8a7f98962382bb5931a150b042bf889d0b70b5.
> Revert "Merge pull request #317 from navikt/java11"

- api-app/src/main/java/no/nav/apiapp/ApiApp.java
- api-app/src/main/java/no/nav/apiapp/ShutdownHook.java
Graceful shutdown should be handled by StatisticsHandler
> Revert sleep in ShutdownHook

- metrics/src/main/java/no/nav/metrics/MetricsConfig.java
- metrics/src/main/java/no/nav/metrics/handlers/SensuHandler.java
Endringer i default verdier:
Timeout: 500ms -> 1000ms
Batches pr sec: 50 -> 20
> La til mulighet for å overstyre sensu connect timeout og endret defaults

- oidc/src/main/java/no/nav/common/oidc/auth/OidcAuthenticationFilter.java
- oidc/src/main/java/no/nav/common/oidc/utils/CookieUtils.java
- oidc/src/test/java/no/nav/common/oidc/OidcAuthenticationFilterTest.java
Revert "bevarer domain/path for cookies ved refresh" og hardkoder bare pathen som cookien får ved refresh til "/"
> Refresh av id_token

- abac/src/main/java/no/nav/common/abac/AbacHttpClient.java
- health/src/main/java/no/nav/common/health/HealthCheckUtils.java
Manglet Authorization header for ping request mot abac
> Fixed ABAC health check

- rest/src/main/java/no/nav/common/rest/client/RestClient.java
Nyttig ved lokal kjøring hvor man gjerne vil skru av sertifikat-sjekking
> La til mulighet for overskriving av default RestClient

- rest/src/main/java/no/nav/common/rest/client/RestUtils.java
- rest/src/test/java/no/nav/common/rest/client/RestUtilsTest.java
I tilfeller hvor man får f.eks 204 vil body være tom men ikke null.
> Forbedre sjekk på empty body

- client/src/main/java/no/nav/common/client/aktorregister/AktorregisterClient.java
- client/src/main/java/no/nav/common/client/aktorregister/AktorregisterHttpClient.java
Fikser feil i uthenting av alle aktørider på bruker, for metrikker
> Fikser feil i uthenting av alle aktørider på bruker

- abac/pom.xml
- auth/pom.xml
- bom/pom.xml
- client/pom.xml
- cxf/pom.xml
- feature-toggle/pom.xml
- health/pom.xml
- job/pom.xml
- log/pom.xml
- metrics/pom.xml
- nais/pom.xml
- pom.xml
- rest/pom.xml
- sts/pom.xml
- test/pom.xml
- types/pom.xml
- util/pom.xml
Endret oppsett slik at hver modul må sette opp avhengigheter for junit 4 eller 5
> bump junit og junit-vintage-engine

- kafka/src/main/java/no/nav/common/kafka/util/KafkaPropertiesBuilder.java
max.poll.interval.ms må konfigureres med int og ikke long
> Fikset feil i consumer properties

- kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/OracleConsumerRepository.java
- kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/PostgresConsumerRepository.java
- kafka/src/main/java/no/nav/common/kafka/producer/feilhandtering/OracleProducerRepository.java
- kafka/src/main/java/no/nav/common/kafka/producer/feilhandtering/PostgresProducerRepository.java
- kafka/src/main/java/no/nav/common/kafka/util/DatabaseUtils.java
Connection må lukkes etter hver spørring i tillegg til PreparedStatement
> Fikset connection lekkasje i consumer/producer repository

- kafka/src/main/java/no/nav/common/kafka/consumer/KafkaConsumerClient.java
- kafka/src/test/java/no/nav/common/kafka/consumer/KafkaConsumerClientTest.java
Fra KafkaConsumer.commitSync dokumentasjon: The committed offset should be the next message your application will consume, i.e. lastProcessedMessageOffset + 1.
> Endrer commit av offset til neste melding som skal konsumeres

- sts/src/main/java/no/nav/common/sts/AzureAdServiceTokenProvider.java
- sts/src/main/java/no/nav/common/sts/ServiceToServiceTokenProvider.java
- sts/src/test/java/no/nav/common/sts/AzureAdServiceTokenProviderTest.java
Gjorde om på rekkefølge av argumenter for getServiceToken(...) slik at interfacet blir mer likt
> Refaktorer service to service token provider

- kafka/src/main/java/no/nav/common/kafka/consumer/feilhandtering/OracleConsumerRepository.java
- kafka/src/main/java/no/nav/common/kafka/producer/feilhandtering/OracleProducerRepository.java
- kafka/src/main/java/no/nav/common/kafka/util/DatabaseUtils.java
Oracle driveren vi bruker støtter ikke createArrayOf.
> Endrer Oracle query fra bruk av ANY til IN

- bom/pom.xml
- client/src/main/java/no/nav/common/client/aktoroppslag/AktorOppslagClient.java
- client/src/main/java/no/nav/common/client/aktoroppslag/BrukerIdenter.java
- client/src/main/java/no/nav/common/client/aktoroppslag/CachedAktorOppslagClient.java
- client/src/main/java/no/nav/common/client/aktoroppslag/PdlAktorOppslagClient.java
- client/src/main/java/no/nav/common/client/aktoroppslag/ToggledAktorOppslagClient.java
- client/src/main/java/no/nav/common/client/aktorregister/AktorregisterHttpClient.java
- client/src/main/resources/pdl/hent-identer-med-hist.graphql
- client/src/test/java/no/nav/common/client/aktoroppslag/CachedAktorOppslagClientTest.java
- client/src/test/java/no/nav/common/client/aktoroppslag/PdlAktorOppslagClientTest.java
- client/src/test/java/no/nav/common/client/aktorregister/AktorregisterHttpClientTest.java
- client/src/test/resources/no/nav/common/client/aktorregister/hent-identer-med-historikk.json
- client/src/test/resources/no/nav/common/client/pdl/aktor_oppslag/hent-identer-request.json
- client/src/test/resources/no/nav/common/client/pdl/aktor_oppslag/hent-identer-response.json
Implementert for både Aktørregister og PDL.
> Funksjonalitet for å hente både gjeldende og historiske fnr og aktør id

- auth/src/main/java/no/nav/common/auth/oidc/filter/AzureAdUserRoleResolver.java
- auth/src/main/java/no/nav/common/auth/oidc/filter/OidcAuthenticationFilter.java
- auth/src/main/java/no/nav/common/auth/oidc/filter/OidcAuthenticatorConfig.java
- auth/src/main/java/no/nav/common/auth/oidc/filter/UserRoleResolver.java
- auth/src/test/java/no/nav/common/auth/oidc/filter/AzureAdUserRoleResolverTest.java
- auth/src/test/java/no/nav/common/auth/oidc/filter/OidcAuthenticationFilterTest.java
Co-authored-by: Alexander Gård <alexander.gard@nav.no>
> Legger inn støtte for azure ad token

- auth/src/main/java/no/nav/common/auth/context/AuthContextHolder.java
- auth/src/test/java/no/nav/common/auth/context/AuthContextHolderTest.java
Inkluderer å hente ident fra pid-claim for eksterne brukere med fallback til sub-claim. Endring i idporten gjør at loginservice vil flytte brukers ident til pid. Vi må derfor sjekke dette før vi evt bruker en fallback til sub.
> Metode for å hente ident til innlogget bruker

- client/src/main/java/no/nav/common/client/norg2/CachedNorg2Client.java
- client/src/main/java/no/nav/common/client/norg2/Norg2Client.java
- client/src/main/java/no/nav/common/client/norg2/NorgHttp2Client.java
- client/src/test/java/no/nav/common/client/norg2/CachedNorg2ClientTest.java
- client/src/test/java/no/nav/common/client/norg2/Norg2HttpClientTest.java
Legg til støtte for å sende med query params mot /api/v1/enhet/navkontor/
> Utvid Norg2Client

- abac/src/main/java/no/nav/common/abac/AbacHttpClient.java
Gjør det mulig å bruke egen token provider så AbacHttpClient kan brukes mot abac-veilarb-proxy
> Ny konstruktør for abac client

- bom/pom.xml
> Oppgrader Kafka til 3.2.3

- audit-log/README.md
Fint om denne kunne oppdateres :)
> Endret navn på Slack Kanal Auditlogg.

- cxf/src/main/java/no/nav/common/cxf/OnBehalfOfWithOidcCallbackHandler.java
- kafka/src/test/java/no/nav/common/kafka/utils/LocalOracleH2Database.java
- pom.xml
- Oppgradert H2 for å få redusert antall sårbarheter (en versjon helt uten kjente sårbarheter finnes dessverre ikke)
- Fjernet XXE-sårbarhet
> Sikkerhetsoppdateringer

- log/src/main/java/no/nav/common/log/MaskedLoggingEvent.java
- pom.xml
Workaround for logstash issue
https://github.com/logfellow/logstash-logback-encoder/issues/939
> workaround_for_logstash_bug

- kafka/pom.xml
- pom.xml
Fikser CVE-2022-45688: https://github.com/advisories/GHSA-3vqj-43w4-2q58
> oppgrader everit-json-schema og json-java

- pom.xml
> bump okhttp

- .github/workflows/main.yml
- .github/workflows/sonarcloud.yml
- abac/pom.xml
- auth/pom.xml
- auth/src/main/java/no/nav/common/auth/oidc/OidcTokenValidator.java
- client/pom.xml
- cxf/pom.xml
- cxf/src/test/java/no/nav/common/cxf/jetty/ToUrl.java
- feature-toggle/pom.xml
- job/pom.xml
- json/pom.xml
- json/src/test/java/no/nav/common/json/TestUtilsTest.java
- kafka/pom.xml
- kafka/src/test/java/no/nav/common/kafka/consumer/feilhandtering/KafkaConsumerRecordProcessorIntegrationTest.java
- log/pom.xml
- metrics/pom.xml
- metrics/src/test/java/no/nav/common/metrics/SocketIntegrasjonTest.java
- nais/pom.xml
- pom.xml
- rest/pom.xml
- sts/pom.xml
- test/pom.xml
- test/src/test/java/no/nav/common/test/SystemPropertiesTest.java
- token-client/src/main/java/no/nav/common/token_client/utils/OidcDiscoveryClient.java
- types/pom.xml
- util/pom.xml
- util/src/test/java/no/nav/common/utils/NaisUtilsTest.java
Jeg har også fjernet avhengigheten til gamle junit (erstattet av junit-jupiter) og fikset noen småting som var deprecated.
> oppdaterer til java 21, og oppdaterer diverse avhengigheter

- kafka/pom.xml
- pom.xml
> Make avro deps optional. Means that users of kafka module needs to pull in avro themselves if they are using avro.
